export const userData = { 
    nickname: "CurvedButterfly",
    streakDays: 45,
    totalPoints: 2850,
    level: 8,
    nextLevelPoints: 3000,
    badges: [
      { id: 1, name: "Brace Boss", description: "Wore your brace for 100+ hours", earned: true, date: "2023-04-15" },
      { id: 2, name: "Physio Warrior", description: "Completed 30 physio sessions", earned: true, date: "2023-03-22" },
      { id: 3, name: "Streak Master", description: "Maintained a 30-day streak", earned: true, date: "2023-05-01" },
      { id: 4, name: "Pain Tracker", description: "Logged pain levels for 14 consecutive days", earned: true, date: "2023-04-10" },
      { id: 5, name: "Community Guide", description: "Helped 10 other users in the community", earned: false },
      { id: 6, name: "Exercise Expert", description: "Tried all exercises in your program", earned: false },
      { id: 7, name: "Sleep Champion", description: "Logged sleep quality for 21 days", earned: false },
      { id: 8, name: "Mood Master", description: "Tracked your mood for 30 days straight", earned: false },
    ],
    weeklyProgress: {
      physio: 4,
      physioGoal: 5,
      brace: 68,
      braceGoal: 112,
      painLogs: 6,
      painLogsGoal: 7,
    },
    leaderboard: [
      { rank: 1, name: "SpineAligned", points: 4250, streak: 120 },
      { rank: 2, name: "CurveFighter", points: 3800, streak: 95 },
      { rank: 3, name: "PostureQueen", points: 3200, streak: 78 },
      { rank: 4, name: "CurvedButterfly", points: 2850, streak: 45 },
      { rank: 5, name: "BraceWarrior", points: 2600, streak: 38 },
    ],
    rewards: [
      { id: 1, name: "Custom App Theme", points: 1000, claimed: true },
      { id: 2, name: "Digital Sticker Pack", points: 2000, claimed: true },
      { id: 3, name: "Exclusive Avatar", points: 3000, claimed: false },
      { id: 4, name: "Premium Workout", points: 5000, claimed: false },
    ],
    dailyTasks: [
      { id: 1, name: "Complete physio session", points: 50, completed: true },
      { id: 2, name: "Log your pain level", points: 25, completed: true },
      { id: 3, name: "Track your mood", points: 25, completed: false },
      { id: 4, name: "Wear brace for goal hours", points: 50, completed: false },
      { id: 5, name: "Read one community post", points: 15, completed: true },
    ],
  }   